FOLDERNAME="Test"
ALBUM_NAME = "SSN TEXST 3"
LOCAL_PHOTOS_FOLDER_PATH = "/Users/bala/Desktop/"+FOLDERNAME+"/GoogleAlbum"
ARCHIVE_FOLDER_PATH = "/Users/bala/Desktop/"+FOLDERNAME+"/GoogleAlbum/Archive"
CREDENTIAL_FILE = "creds.json"
ERROR_FOLDER_PATH = "/Users/bala/Desktop/"+FOLDERNAME+"/GoogleAlbum/Error"