LOCAL_PHOTOS_FOLDER_PATH = "/Users/bala/Desktop/2023/July 30 Arangetram/Web"
ALBUM_NAME = "Kaviyum Nanum Function | July 30 | 2023"
ARCHIVE_FOLDER_PATH = "/Users/bala/Desktop/2023/July 30 Arangetram/Web/Archive"
CREDENTIAL_FILE = "creds.json"
ERROR_FOLDER_PATH = "/Users/bala/Desktop/2023/July 30 Arangetram/Web/Error"