LOCAL_PHOTOS_FOLDER_PATH = "/Volumes/BalaSSD 1/Mac/Temp/Temple Day 5 Aug 31/Pics/Web"
ALBUM_NAME = "HTKY Aug 31"
ARCHIVE_FOLDER_PATH = "/Volumes/BalaSSD 1/Mac/Temp/Temple Day 5 Aug 31/Pics/Web/Archive"
CREDENTIAL_FILE = "creds.json"
ERROR_FOLDER_PATH = "/Volumes/BalaSSD 1/Mac/Temp/Temple Day 5 Aug 31/Pics/Web/Error"